x = input('Digite algo: ')
print(type(x))
print('É alfanumérico? ', x.isalnum())
print('É Alfabético? ', x.isalpha())
print('É numérico? ', x.isnumeric())
print('Está em caixa alta?', x.isupper())
print('Está em minúsculas?', x.islower())
print('É espaço? ', x.isspace())
print('Está capitalizado? ', x.istitle())