n = input('Qual é o seu nome? ')
print('Seja bem-vindo(a), {}!'.format(n))
print('Seja bem-vindo(a), {:20}!'.format(n))
print('Seja bem-vindo(a), {:>20}!'.format(n))
print('Seja bem-vindo(a), {:<20}!'.format(n))
print('Seja bem-vindo(a), {:^20}!'.format(n))
print('Seja bem-vindo(a), {:-^20}!'.format(n))